### ISSUE TITLE
Offer as MIT license?

### ISSUE THREAD

**Issue by somerandomdude** [antelle/wasm-image-compressor#2]
Hi there, I was wondering if you'd be willing to release this under the MIT license. Is there any flexibility in changing this?

Thanks!

**Comment by antelle** [comment]
Nope, pngquant is GPL: https://pngquant.org/lib/
I actually don't have anything else here, it's just pngquant compiled for web + a couple of buttons.

**Comment by somerandomdude** [comment]
_Ah_. Got it. Thanks so much for the quick response!
