### ISSUE TITLE
additional content appears on the compressed image

### ISSUE THREAD

**Issue by IYOUR** [antelle/wasm-image-compressor#3]
> ### **When I have selected dithering value, some additional content appears on the compressed image.**

![截屏2022-03-20 17.13.07.png](https://s2.loli.net/2022/03/20/DibVs9fq7QIrmhG.png)

**Comment by antelle** [comment]
Just in case, it's not a product, but rather a demo of using the library in wasm. So, if you want, feel free to submit a pr.

**Comment by IYOUR** [comment]
Oh, I see.
Thanks
